---
title: "Post offices"
author: "Jeff Grayum"
date: "1/8/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries.
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
#install.packages("historydata")
library(historydata)
library(gganimate)
```

Loading dataset.
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-04-13')

post_offices <- tuesdata$post_offices

post_offices %>%
  view()
```

Getting started...
```{r}
post_offices %>%
  count(id, sort = TRUE)

post_offices %>%
  count(name, sort = TRUE)

post_offices %>%
  count(name, orig_name, state, sort = TRUE)

post_offices %>%
  filter(county1 == "GRAND TRAVERSE", name == "ACME") %>%
  view()

post_offices %>%
  add_count(name, orig_name, state, county1, sort = TRUE) %>%
  filter(n >= 2) %>%
  arrange(name, orig_name, state, county1) %>%
  view()

post_offices <- tuesdata$post_offices %>%
  select(name, state, county1, established, discontinued, continuous, stamp_index, id, coordinates, latitude, longitude, gnis_dist, gnis_county, gnis_state) %>%
  filter(established >= 1750,
       is.na(discontinued) |  discontinued >= established)

post_office_years <- post_offices %>%
  select(name, state, established, discontinued, latitude, longitude) %>%
  replace_na(list(discontinued = 2003)) %>%
  filter(discontinued <= 2021) %>%
  mutate(year = map2(established, discontinued, seq)) %>%
  unnest(year)
  
  post_office_years %>%
  count(year, name = "n_post_offices") %>%
  ggplot(aes(year, n_post_offices)) +
  geom_area() +
    labs(x = "Year",
         y = "# of post offices",
         title = "Number of post offices in the US") +
    theme_hc()
```


```{r}
 post_offices_cumulative <-  post_office_years %>%
  count(year,
        state = fct_lump(state, 16),
        name = "n_post_offices") 

post_offices_cumulative %>%
  filter(state != "Other") %>%
  mutate(state = fct_reorder(state, -n_post_offices, sum)) %>%
  ggplot(aes(year, n_post_offices, fill = state)) +
  geom_area() +
    labs(x = "Year",
         y = "# of post offices",
         title = "Number of post offices in the US",
         fill = "State") +
    theme_hc() +
  theme(legend.position = "none") +
  facet_wrap(~ state)
```

Let's look at closures per decade.
```{r}
post_offices %>%
  filter(!is.na(discontinued)) %>%
  count(state,
           decade = 10 * (discontinued %/% 10),
        name = "n_closures") %>%
  filter(state == "KY") %>%
  ggplot(aes(decade, n_closures)) +
  geom_area() +
  labs(x = "Decade",
       y = "# of PO closures",
       title = "Number of post offices closed per decade:",
       subtitle = "Kentucky") +
  theme_hc()

post_office_closures <- post_offices %>%
  filter(!is.na(discontinued),
         established >= 1750,
         discontinued >= 1750,
         discontinued <= 2021) %>%
  count(state = fct_lump(state, 16),
        decade = 10 * (discontinued %/% 10),
        name = "n_closures") 

post_office_closures %>%
  mutate(state = fct_reorder(state, -n_closures, sum)) %>%
  filter(state != "Other") %>%
  ggplot(aes(decade, n_closures, fill = state)) +
  geom_area() +
  labs(x = "Decade",
       y = "# of post offices closed in this decade",
       title = "When and where were the most post offices closed?") +
  facet_wrap(~ state) +
  theme_hc() +
  theme(legend.position = "none") 
  
```


```{r}
post_office_closures %>%
  filter(decade < 2000) %>%
  inner_join(post_offices_cumulative, by = c("state", "decade" = "year")) %>%
  mutate(pct_closed = n_closures / n_post_offices) %>%
  filter(n_post_offices >= 50,
         state %in% c("KY", "PA")) %>%
  ggplot(aes(decade, pct_closed, color = state)) +
  geom_line() +
  scale_y_continuous(labels = percent) +
  labs(x = "Decade",
       y = "% of post offices closed",
       color = "State") +
  theme_hc()
```


Let's make some maps.
```{r}
post_office_years %>%
  filter(year == 2003) %>%
  count(state, sort = TRUE) 

states_map <- map_data("state") %>%
  as_tibble() %>%
  mutate(state = state.abb[match(region, str_to_lower(state.name))]) %>%
  replace_na(list(state = "DC"))

post_office_years %>%
  filter(year == 2000) %>%
  count(state, sort = TRUE) %>%
  inner_join(states_map, by = "state") %>%
  ggplot(aes(long, lat, group = group, fill = n)) +
  geom_polygon() + 
  scale_fill_gradient2(low = "blue", high = "red", midpoint = 750) +
  theme_map() +
  labs(fill = "# of post offices in 2003")

state_pop_2000 <- us_state_populations %>%
  filter(year == 2000) %>%
  mutate(state = state.abb[match(state, state.name)]) %>%
  replace_na(list(state = "DC"))

post_office_years %>%
  filter(year == 2000) %>%
  count(state, sort = TRUE) %>%
  inner_join(state_pop %>%
               filter(year == 2000), by = "state") %>%
  inner_join(states_map, by = "state") %>%
  mutate(post_office_density = n / (population / 1e6)) %>%
  ggplot(aes(long, lat, group = group, fill = post_office_density)) +
  geom_polygon() + 
  scale_fill_gradient2(low = "blue", high = "red", midpoint = 250) +
  theme_map() +
  labs(fill = "Post offices / million people")

state_pop <- us_state_populations %>%
  mutate(state = state.abb[match(state, state.name)]) %>%
  replace_na(list(state = "DC"))
```

Let's make that map pretty and make it dance.
```{r}
 post_offices_cumulative_all <-  post_office_years %>%
  count(year,
        state,
        name = "n_post_offices") 

by_state_year <- post_offices_cumulative_all %>%
  left_join(state_pop, by = c("year", "state")) %>%
  mutate(post_office_density = n_post_offices / (population / 1e6)) 

by_state_year %>%
  filter(year %in% c(1800, 1850, 1900, 1950)) %>%
  inner_join(states_map, by = "state") %>%
  ggplot(aes(long, lat, group = group, fill = n_post_offices)) +
  geom_polygon() + 
  scale_fill_gradient2(low = "blue", high = "red", mid = "pink", midpoint = 2000) +
  theme_map() +
  labs(fill = "Post offices") +
  facet_wrap(~ year) 
  
by_state_year %>%
  filter(year %% 5 == 0) %>%
  inner_join(states_map, by = "state") %>%
  ggplot(aes(long, lat, group = group, fill = n_post_offices)) +
  geom_polygon() + 
  scale_fill_gradient2(low = "blue", high = "red", mid = "pink", midpoint = 2000) +
  transition_manual(year) +
  theme_map() +
  labs(fill = "Post offices",
       title = "Number of post offices in the year {current_frame}") 

```

```{r}
post_office_years %>%
  filter(year == 1900,
         !state %in% c("HI", "AK")) %>%
  ggplot(aes(longitude, latitude)) +
  borders("state") +
  geom_point(size = .02) +
  theme_map() +
  coord_map()

 post_office_years %>%
  filter(year == 2000,
         !state %in% c("HI", "AK")) %>%
  ggplot(aes(longitude, latitude)) +
  borders("state") +
  geom_point(size = .02) +
  theme_map() +
  coord_map()
 
  post_office_years %>%
  filter(year %% 60 == 0,
         !state %in% c("HI", "AK")) %>%
  ggplot(aes(longitude, latitude)) +
  borders("state") +
  geom_point(size = .02, alpha = 0.3) +
  theme_map() +
  coord_map() +
  facet_wrap(~ year)
  
  
post_office_years %>%
  filter(year %% 2 == 0,
         !state %in% c("HI", "AK")) %>%
  ggplot(aes(longitude, latitude)) +
  borders("state") +
  geom_point(size = .02, alpha = 0.25) +
  transition_manual(year) +
  labs(title = "Number of post offices in the year { current_frame}") +
  theme_map() +
  coord_map()
```






